DATA:
  data_root: data/matterport_3d
  data_root_2d_fused_feature: data/matterport_multiview_lseg
  feature_2d_extractor: lseg
  classes: 21
  aug: True
  voxel_size: 0.02
  input_color: False
  use_shm: False
  
DISTILL:
  arch_3d: MinkUNet18A
  ignore_label: 255
  train_gpu: [0]
  workers: 8  # data loader workers
  batch_size: 8  # batch size for training
  batch_size_val: 1  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.0001
  loss_type: cosine # l1 | cosine
  loop: 5
  epochs: 100
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  manual_seed: 3407
  print_freq: 10
  save_freq: 1
  save_path:
  resume:
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1

TEST:
  split: test  # split in [train, val