DATA:
  data_root: ./dma_remove/data/data_scannet/scannet_3d
  data_root_2d_fused_feature: ./dma_remove/data/data_scannet/scannet_multiview_openseg
  feature_2d_extractor: openseg
  classes: 20
  aug: True
  voxel_size: 0.02
  input_color: False
  use_shm: False
  
DISTILL:
  arch_3d: MinkUNet18A
  ignore_label: 255
  train_gpu: [0]
  # train_gpu: [0]
  workers: 8  # data loader workers
  batch_size: 6  # batch size for training
  batch_size_val: 1  # batch size for validation during training, memory and speed tradeoff
 