DATA:
  data_root: ./dma_remove/data/data_scannet/scannet_3d
  data_root_2d_fused_feature: ./dma_remove/data/data_scannet/scannet_multiview_openseg
  feature_2d_extractor: openseg
  classes: 20
  aug: True
  voxel_size: 0.02
  input_color: False
  use_shm: False
  
DISTILL:
  arch_3d: MinkUNet18A
  ignore_label: 255
  train_gpu: [0]
  # train_gpu: [0]
  workers: 8  # data loader workers
  batch_size: 6  # batch size for training
  batch_size_val: 1  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.0001
  base_weight: 0.1
  loss_type: cosine # l1 | cosine
  loop: 5
  epochs: 100
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  manual_seed: 1463
  print_freq: 10
  save_freq: 1
  save_path:
  # resume: ./output_7_best/model/model_best.pth.tar
  # resume: './scannet_openseg.pth.tar'
  resume:
  evaluate: True  # evaluate on validation set, extra gpu memory needed an