DATA:
  data_root: data/scannet_3d
  data_root_2d_fused_feature: data/scannet_multiview_lseg
  feature_2d_extractor: lseg
  classes: 20
  aug: True
  voxel_size: 0.02
  input_color: False
  use_shm: False
  
DISTILL:
  arch_3d: MinkUNet18A
  ignore_label: 255
  train_gpu: [0]
  workers: 8  # data loader workers
  batch_size: 8  # batch size for train