DATA:
  data_root: data/replica_processed/replica_3d
  data_root_2d_fused_feature: data/replica_multiview_openseg
  feature_2d_extractor: openseg
  voxel_size: 0.02
  input_color: False
  use_shm: False
  
TEST:
  split:
  labelset: matterport
  prompt_eng: True
  mark_no_feature_to_unknown: True
  feature_type: 'ensemble' # 'distill' | 'fusion' | 'ensemble'
  save_feature_as_numpy: False
  eval_iou: False
  vis_input: True
  vis_pred: True
  test_workers: 0
  test_gpu: [0]
  test_batch_size: 1
  model_path: